pull_request_rules:
- name: label scala-steward's PRs
  conditions:
  - author=scala-steward
  actions:
    label:
      add:
      - dependency-update
      remove: []
- name: merge scala-steward's PRs
  conditions:
  - author=scala-steward
  - status-success=Build and Test (ubuntu-latest, 2.13.10, temurin@17)
  - status-success=Build and Test (ubuntu-latest, 2.13.10, temurin@11)
  actions:
    merge:
      method: squash